const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('tokenCompanion', {
  snapshot: () => ipcRenderer.invoke('snapshot'),
  getState: () => ipcRenderer.invoke('get-state'),
  catalog: () => ipcRenderer.invoke('catalog'),
  reset: () => ipcRenderer.invoke('reset-companion'),
  replayCaught: (id) => ipcRenderer.invoke('replay-caught', id),
  hatchEgg: (id) => ipcRenderer.invoke('hatch-egg', id),
  releaseEgg: (id) => ipcRenderer.invoke('release-egg', id),
  claimFreeEgg: () => ipcRenderer.invoke('claim-free-egg'),
  getEggClaimStatus: () => ipcRenderer.invoke('egg-claim-status'),
  swapActive: (id) => ipcRenderer.invoke('swap-active', id),
  swapEggToActive: (id) => ipcRenderer.invoke('swap-egg-to-active', id),
  confirm: (opts) => ipcRenderer.invoke('confirm', opts),
  setTeam: (ids) => ipcRenderer.invoke('set-team', ids),
  releaseCaught: (id, force) => ipcRenderer.invoke('release-caught', id, force),
  createTrade: (id) => ipcRenderer.invoke('create-trade', id),
  claimTrade: (code, id) => ipcRenderer.invoke('claim-trade', code, id),
  createRemoteTrade: (id, relayUrl) => ipcRenderer.invoke('remote-trade-create', id, relayUrl),
  joinRemoteTrade: (code, id, relayUrl) => ipcRenderer.invoke('remote-trade-join', code, id, relayUrl),
  confirmRemoteTrade: (code, relayUrl) => ipcRenderer.invoke('remote-trade-confirm', code, relayUrl),
  remoteTradeStatus: (code, relayUrl) => ipcRenderer.invoke('remote-trade-status', code, relayUrl),
  createRemoteBattle: (relayUrl) => ipcRenderer.invoke('remote-battle-create', relayUrl),
  joinRemoteBattle: (code, relayUrl) => ipcRenderer.invoke('remote-battle-join', code, relayUrl),
  remoteBattleStatus: (code, relayUrl) => ipcRenderer.invoke('remote-battle-status', code, relayUrl),
  startTradeRelay: () => ipcRenderer.invoke('start-trade-relay'),
  autoBattle: (opponent) => ipcRenderer.invoke('auto-battle', opponent),
  getPracticeTiers: () => ipcRenderer.invoke('get-practice-tiers'),
  getTowerStatus: () => ipcRenderer.invoke('tower-status'),
  startTowerRun: () => ipcRenderer.invoke('tower-start'),
  battleTowerFloor: () => ipcRenderer.invoke('tower-battle'),
  resetTowerRun: () => ipcRenderer.invoke('tower-reset'),
  settings: () => ipcRenderer.invoke('settings'),
  setLaunchAtLogin: (enabled) => ipcRenderer.invoke('set-launch-at-login', enabled),
  setLanguage: (language) => ipcRenderer.invoke('set-language', language),
  notify: (title, body) => ipcRenderer.invoke('notify', title, body),
  checkForUpdate: (url) => ipcRenderer.invoke('check-for-update', url),
  applyUpdate: (downloadUrl, filename) => ipcRenderer.invoke('apply-update', downloadUrl, filename),
  setMasterMode: (isMaster) => ipcRenderer.invoke('set-master-mode', isMaster),
  getUpdaterStatus: () => ipcRenderer.invoke('get-updater-status'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (_, data) => callback(data)),
  onUpdateProgress: (callback) => ipcRenderer.on('update-download-progress', (_, data) => callback(data)),
  onRefresh: (callback) => ipcRenderer.on('refresh-requested', callback),
  verifyAdminCode: (code) => ipcRenderer.invoke('verify-admin-code', code),
  adminAction: (action, payload) => ipcRenderer.invoke('admin-action', action, payload)
});
